spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nofap
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  jackson:
    time-zone: Asia/Tashkent
  

sentry:
  dsn: https://5e702e1d33077919152dca5d1fc4e77a@o4509339210809344.ingest.de.sentry.io/4509339212447824
  environment: production
  release: kuchtop@1.0.0
  traces-sample-rate: 1.0
  debug: true

bot:
  token: 8155117188:AAFz_IFtGzFRcN4yj9IiI-Lul11zIR9BuV0
  username: neverfapnofapantipornbot
server:
  port: 8080

