spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nofap
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379


bot:
  token: 8155117188:AAFz_IFtGzFRcN4yj9IiI-Lul11zIR9BuV0
  username: neverfapnofapantipornbot