spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kuchtop_db
    username: kuchtop_user
    password: strongpassword
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379


bot:
  token: 8155117188:AAFz_IFtGzFRcN4yj9IiI-Lul11zIR9BuV0
  username: neverfapnofapantipornbot