server:
  port: 8090

spring:
  task:
    scheduling:
      pool:
        size: 10
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5433/willup
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

bot:
  token: 7531833643:AAG9o0sQPIief9bm9-unEuKaJmfjb22XkCg
  username: KuchtopBot

sentry:
  dsn: https://5e702e1d33077919152dca5d1fc4e77a@o4509339210809344.ingest.de.sentry.io/4509339212447824
  environment: production
  release: kuchtop@1.0.0
  traces-sample-rate: 1.0
  debug: true